# Generated by Django 4.1.7 on 2023-03-10 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=127)),
                ("number", models.IntegerField()),
                ("district", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("code_zip", models.CharField(max_length=10)),
            ],
        ),
    ]
