# Generated by Django 4.1.7 on 2023-03-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=127)),
                ("number", models.IntegerField()),
                ("district", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
    ]
