# Generated by Django 4.0.7 on 2023-03-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='code_zip',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
