# Generated by Django 4.1.7 on 2023-03-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="returned_at",
            new_name="should_returned_at",
        ),
    ]
