# Generated by Django 4.1.7 on 2023-03-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copies", "0003_rename_returned_at_borrowing_should_returned_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="should_returned_at",
            new_name="should_return_at",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="returned_at",
            field=models.DateField(default=None, null=True),
        ),
    ]
